DROP TABLE IF EXISTS REGION_MAPPING;
DROP TABLE IF EXISTS CONSTELLATION_INCURSION_MAPPING;
DROP TABLE IF EXISTS SOVEREIGNTY_MAPPING;
DROP TABLE IF EXISTS SYSTEM_JUMPS_MAPPING;
DROP TABLE IF EXISTS SYSTEM_KILLS_MAPPING;
CREATE TABLE REGION_MAPPING AS SELECT * FROM CSVREAD('src\main\resources\REGION_MAPPING.csv');